shAttack Attacks[kAttNumberOf] =
{
   {  // Dummy
      shAttack::kNoAttack,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ImprovisedMelee
      shAttack::kSmash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      -4,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ImprovisedThrow
      shAttack::kSmash,
      shAttack::kSingle,
      kMissile,
      0,
      0,
      -4,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            2,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // GroundCollision
      shAttack::kSmash,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // KickedWall
      shAttack::kSmash,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            2,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // KickedForceField
      shAttack::kSmash,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            3,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PitTrapFall
      shAttack::kSmash,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AcidPitBath
      shAttack::kAcidBath,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kCorrosive,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AcidPitSip
      shAttack::kNoAttack,
      shAttack::kOther,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kCorrosive,
            3,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // RadTrap
      shAttack::kGammaRay,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kRadiological,
            11,
            20,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // DoorSlam
      shAttack::kCrush,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AcidBlood1
      shAttack::kAcidSplash,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kCorrosive,
            2,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AcidBlood2
      shAttack::kAcidSplash,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kCorrosive,
            12,
            24,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ExplodingMonster
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            6,
            18,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // VatCorrosion
      shAttack::kSlime,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kCorrosive,
            1,
            5,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // VatShock
      shAttack::kZap,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kElectrical,
            5,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // VatPoison
      shAttack::kNoAttack,
      shAttack::kOther,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kToxic,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // VatPlague
      shAttack::kPlague,
      shAttack::kOther,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kIrresistible,
            10,
            30,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // FallingVat
      shAttack::kSmash,
      shAttack::kSingle,
      kMissile,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            10,
            30,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // RestrainingBoltWear
      shAttack::kZap,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kBugging,
            1,
            1,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // RestrainingBoltAttack
      shAttack::kAttach,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // TorcRemoval
      shAttack::kZap,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kElectrical,
            4,
            9,
            100
         },
         {
            kPsychic,
            4,
            9,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Glory1
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      2,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            6,
            18,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Glory2
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      4,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            8,
            24,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Glory3
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      6,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            12,
            36,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Glory4
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      8,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            18,
            54,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Glory5
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      24,
      0,
      0,
      FULLTURN,
      {
         {
            kDisintegrating,
            500,
            500,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Shuriken
      shAttack::kStab,
      shAttack::kSingle,
      kMissile,
      0,
      15,
      0,
      HALFTURN,
      {
         {
            kHackNSlash,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // SmartDiscSlash
      shAttack::kSlash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            2,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // SmartDiscThrow
      shAttack::kDisc,
      shAttack::kSmartDisc,
      kMissile,
      0,
      15,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            2,
            7,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ThrownFootball
      shAttack::kSmash,
      shAttack::kSingle,
      kMissile,
      0,
      10,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // KickedFootball
      shAttack::kSmash,
      shAttack::kSingle,
      kMissile,
      0,
      20,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Dagger
      shAttack::kStab,
      shAttack::kSingle,
      (kMelee | kMissile),
      0,
      10,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Probe
      shAttack::kAnalProbe,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kViolating,
            10,
            100,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Club
      shAttack::kClub,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Wrench
      shAttack::kClub,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            2,
            7,
            100
         },
         {
            kStunning,
            2,
            2,
            20
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // MopBo
      shAttack::kSmash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Nunchucks
      shAttack::kClub,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            2,
            9,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // CattleProd
      shAttack::kZap,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kElectrical,
            1,
            4,
            100
         },
         {
            kStunning,
            1,
            2,
            50
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ZapBaton
      shAttack::kZap,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kElectrical,
            1,
            6,
            100
         },
         {
            kParalyzing,
            1,
            2,
            33
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // RazorWhip
      shAttack::kWhip,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      QUICKTURN,
      {
         {
            kConcussive,
            1,
            5,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Chainsaw
      shAttack::kSaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            4,
            14,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // CombiStickStab
      shAttack::kStab,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // CombiStickThrow
      shAttack::kStab,
      shAttack::kSingle,
      kMissile,
      0,
      12,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            4,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // CombiStickExtend
      shAttack::kCombi,
      shAttack::kExtend,
      kMelee,
      0,
      2,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // GomJabbar
      shAttack::kPrick,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kToxic,
            3,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Katana
      shAttack::kSword,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ElvenSword
      shAttack::kSword,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            3,
            5,
            100
         },
         {
            kPsychic,
            1,
            1,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Batleth
      shAttack::kSlash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            2,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ChaosSword
      shAttack::kSword,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            4,
            14,
            100
         },
         {
            kPsychic,
            1,
            1,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Lightsaber
      shAttack::kSword,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            2,
            12,
            100
         },
         {
            kBurning,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // WristBlade
      shAttack::kStab,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PowerFist
      shAttack::kPunch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      SLOWTURN,
      {
         {
            kConcussive,
            3,
            12,
            100
         },
         {
            kStunning,
            1,
            3,
            80
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PowerClaw
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      SLOWTURN,
      {
         {
            kHackNSlash,
            2,
            14,
            100
         },
         {
            kParalyzing,
            1,
            2,
            50
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PhaseGloves
      shAttack::kPunch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            2,
            8,
            100
         },
         {
            kElectrical,
            2,
            5,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PsiBlade
      shAttack::kSlash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kHackNSlash,
            1,
            3,
            100
         },
         {
            kPsychic,
            1,
            1,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ConcussionGrenade
      shAttack::kBlast,
      shAttack::kBurst,
      kMissile,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            3,
            18,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // FragGrenade
      shAttack::kBlast,
      shAttack::kBurst,
      kMissile,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kShrapnel,
            2,
            12,
            100
         },
         {
            kConcussive,
            2,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // StunGrenade
      shAttack::kBlast,
      shAttack::kBurst,
      kMissile,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kStunning,
            3,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // IncendiaryGrenade
      shAttack::kIncendiary,
      shAttack::kBurst,
      kMissile,
      2,
      0,
      0,
      FULLTURN,
      {
         {
            kBurning,
            3,
            9,
            100
         },
         {
            kConcussive,
            2,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // RadGrenade
      shAttack::kFlash,
      shAttack::kBurst,
      kMissile,
      3,
      0,
      0,
      FULLTURN,
      {
         {
            kRadiological,
            15,
            35,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Flashbang
      shAttack::kLight,
      shAttack::kBurst,
      kMissile,
      5,
      0,
      0,
      FULLTURN,
      {
         {
            kBlinding,
            2,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // EMPGrenade
      shAttack::kBlast,
      shAttack::kBurst,
      kMissile,
      2,
      0,
      0,
      FULLTURN,
      {
         {
            kMagnetic,
            3,
            18,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // WebbingGrenade
      shAttack::kEnsnare,
      shAttack::kBurst,
      kMissile,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kWebbing,
            5,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Flare
      shAttack::kFlare,
      shAttack::kBurst,
      kMissile,
      3,
      0,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // HypnoDiskB
      shAttack::kLight,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kMesmerizing,
            12,
            80,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // HypnoDiskD
      shAttack::kLight,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kMesmerizing,
            6,
            40,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // HypnoDiskO
      shAttack::kLight,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kMesmerizing,
            5,
            25,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // SickHypnoDiskB
      shAttack::kLight,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kMesmerizing,
            12,
            80,
            100
         },
         {
            kSickening,
            5,
            10,
            100
         },
         {
            kToxic,
            1,
            3,
            100
         }
      }
   },
   {  // SickHypnoDiskD
      shAttack::kLight,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kMesmerizing,
            6,
            40,
            100
         },
         {
            kSickening,
            3,
            8,
            100
         },
         {
            kToxic,
            1,
            2,
            100
         }
      }
   },
   {  // SickHypnoDiskO
      shAttack::kLight,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kMesmerizing,
            5,
            25,
            100
         },
         {
            kSickening,
            1,
            6,
            100
         },
         {
            kToxic,
            1,
            1,
            100
         }
      }
   },
   {  // HypnoGaze
      shAttack::kNoAttack,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kMesmerizing,
            2,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ShootWeb
      shAttack::kWeb,
      shAttack::kSingle,
      kMissile,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kWebbing,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // OpticBlast
      shAttack::kOpticBlast,
      shAttack::kBeam,
      kAimed,
      0,
      12,
      0,
      FULLTURN,
      {
         {
            kLaser,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // BurningGoggles
      shAttack::kNoAttack,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kBurning,
            6,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // MentalBlast
      shAttack::kMentalBlast,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kPsychic,
            1,
            6,
            100
         },
         {
            kConfusing,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ResistedMentalBlast
      shAttack::kMentalBlast,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kPsychic,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PsionicStorm
      shAttack::kPsionicStorm,
      shAttack::kBurst,
      0,
      4,
      0,
      0,
      FULLTURN,
      {
         {
            kPsychic,
            5,
            25,
            100
         },
         {
            kConfusing,
            3,
            9,
            100
         },
         {
            kStunning,
            3,
            9,
            100
         }
      }
   },
   {  // CaesareanSection
      shAttack::kNoAttack,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kIrresistible,
            6,
            36,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PeaShooter
      shAttack::kPea,
      shAttack::kSingle,
      kAimed,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Pistol
      shAttack::kGun,
      shAttack::kSingle,
      kAimed,
      0,
      60,
      0,
      FULLTURN,
      {
         {
            kBullet,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Khan
      shAttack::kGun,
      shAttack::kSingle,
      kAimed,
      0,
      60,
      0,
      FULLTURN,
      {
         {
            kBullet,
            3,
            9,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Net
      shAttack::kWeb,
      shAttack::kSingle,
      kAimed,
      0,
      8,
      0,
      FULLTURN,
      {
         {
            kWebbing,
            2,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Shotgun
      shAttack::kShot,
      shAttack::kSingle,
      kAimed,
      0,
      10,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            8,
            18,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // SawnoffShotgun
      shAttack::kShot,
      shAttack::kCone,
      kAimed,
      1,
      5,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            2,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Rifle
      shAttack::kGun,
      shAttack::kSingle,
      kAimed,
      0,
      180,
      0,
      FULLTURN,
      {
         {
            kBullet,
            1,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // LFlamer
      shAttack::kIncendiary,
      shAttack::kCone,
      kAimed,
      3,
      6,
      0,
      FULLTURN,
      {
         {
            kBurning,
            2,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // HFlamer
      shAttack::kIncendiary,
      shAttack::kCone,
      kAimed,
      2,
      8,
      0,
      FULLTURN,
      {
         {
            kBurning,
            3,
            18,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Speargun
      shAttack::kSpear,
      shAttack::kSingle,
      kAimed,
      0,
      60,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PulseRifle
      shAttack::kGun,
      shAttack::kSingle,
      kAimed,
      0,
      60,
      0,
      FULLTURN,
      {
         {
            kBullet,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Smartgun
      shAttack::kGun,
      shAttack::kSingle,
      kAimed,
      0,
      60,
      0,
      FULLTURN,
      {
         {
            kBullet,
            1,
            9,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Railgun
      shAttack::kRail,
      shAttack::kSingle,
      kAimed,
      0,
      180,
      0,
      SLOWTURN,
      {
         {
            kBullet,
            3,
            30,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Cannon
      shAttack::kGun,
      shAttack::kSingle,
      kAimed,
      0,
      60,
      0,
      FULLTURN,
      {
         {
            kBullet,
            1,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // LaserPistol
      shAttack::kLaserBeam,
      shAttack::kBeam,
      kAimed,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kLaser,
            1,
            7,
            100
         },
         {
            kBlinding,
            1,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Phaser
      shAttack::kLaserBeam,
      shAttack::kBeam,
      kAimed,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kLaser,
            1,
            8,
            100
         },
         {
            kBlinding,
            1,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Blaster
      shAttack::kBolt,
      shAttack::kSingle,
      kAimed,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kParticle,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PlasmaPistol
      shAttack::kPlasmaGlob,
      shAttack::kSingle,
      kAimed,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kPlasma,
            1,
            10,
            100
         },
         {
            kMagnetic,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ZapGun
      shAttack::kBolt,
      shAttack::kSingle,
      kAimed,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kElectrical,
            1,
            6,
            100
         },
         {
            kParalyzing,
            1,
            2,
            40
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PlasmaCaster0
      shAttack::kPlasmaGlob,
      shAttack::kSingle,
      kAimed,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kPlasma,
            1,
            12,
            100
         },
         {
            kMagnetic,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PlasmaCaster1
      shAttack::kBlast,
      shAttack::kFarBurst,
      kAimed,
      1,
      30,
      0,
      FULLTURN,
      {
         {
            kPlasma,
            3,
            15,
            100
         },
         {
            kMagnetic,
            2,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PlasmaCaster2
      shAttack::kBlast,
      shAttack::kFarBurst,
      kAimed,
      2,
      30,
      0,
      FULLTURN,
      {
         {
            kPlasma,
            3,
            15,
            100
         },
         {
            kMagnetic,
            2,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // LaserRifle
      shAttack::kLaserBeam,
      shAttack::kBeam,
      kAimed,
      0,
      45,
      0,
      FULLTURN,
      {
         {
            kLaser,
            1,
            11,
            100
         },
         {
            kBlinding,
            3,
            15,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PlasmaRifle
      shAttack::kPlasmaGlob,
      shAttack::kSingle,
      kAimed,
      0,
      45,
      0,
      FULLTURN,
      {
         {
            kPlasma,
            2,
            16,
            100
         },
         {
            kMagnetic,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // LaserCannon
      shAttack::kLaserBeam,
      shAttack::kBeam,
      kAimed,
      0,
      30,
      0,
      SLOWTURN,
      {
         {
            kLaser,
            4,
            44,
            100
         },
         {
            kBlinding,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // MiningLaser
      shAttack::kLaserBeam,
      shAttack::kBeam,
      kAimed,
      0,
      0,
      0,
      SLOWTURN,
      {
         {
            kLaser,
            2,
            22,
            100
         },
         {
            kBlinding,
            1,
            4,
            80
         },
         {
            kDigging,
            0,
            0,
            50
         }
      }
   },
   {  // PlasmaCannon
      shAttack::kPlasmaGlob,
      shAttack::kSingle,
      kAimed,
      0,
      30,
      0,
      SLOWTURN,
      {
         {
            kPlasma,
            4,
            40,
            100
         },
         {
            kMagnetic,
            8,
            20,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // UniversalSolvent
      shAttack::kNoAttack,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kCorrosive,
            2,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Plasma
      shAttack::kNoAttack,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kElectrical,
            4,
            24,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Napalm
      shAttack::kNoAttack,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kBurning,
            4,
            24,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // LNO
      shAttack::kNoAttack,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kFreezing,
            4,
            24,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PoisonCanister
      shAttack::kNoAttack,
      shAttack::kSingle,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kToxic,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // GlueSpill
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kParalyzing,
            2,
            5,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // StirredBBB
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kExplosive,
            3,
            9,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // LNOBlast
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kFreezing,
            4,
            32,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // NapalmBlast
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kBurning,
            4,
            32,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PlasmaBlast
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kBurning,
            4,
            32,
            100
         },
         {
            kMagnetic,
            4,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // SolventBlast
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kCorrosive,
            6,
            14,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AntimatterBlast
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      2,
      0,
      0,
      FULLTURN,
      {
         {
            kExplosive,
            4,
            16,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // FreezeRay
      shAttack::kFreezeRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kFreezing,
            4,
            32,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // HeatRay
      shAttack::kHeatRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kBurning,
            4,
            32,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // GaussRay
      shAttack::kGaussRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kMagnetic,
            4,
            32,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PoisonRay
      shAttack::kPoisonRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kToxic,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // StasisRay
      shAttack::kStasisRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kParalyzing,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // GammaRay
      shAttack::kGammaRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kRadiological,
            15,
            45,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // TransporterRay
      shAttack::kTransporterRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kTransporting,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // HealingRay
      shAttack::kHealingRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kSpecial,
            3,
            7,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // RestorationRay
      shAttack::kRestorationRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // DisintegrationRay
      shAttack::kDisintegrationRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kDisintegrating,
            20,
            40,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // DisintegrationRayGunBlowUp
      shAttack::kBlast,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kDisintegrating,
            10,
            30,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AccelerationRay
      shAttack::kAccelerationRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kAccelerating,
            3,
            9,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // DecelerationRay
      shAttack::kDecelerationRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kDecelerating,
            3,
            9,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AugmentationRay
      shAttack::kAugmentationRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // DecontaminationRay
      shAttack::kDecontaminationRay,
      shAttack::kBeam,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kSpecial,
            15,
            30,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // SquirtWater
      shAttack::kWaterRay,
      shAttack::kSingle,
      kAimed,
      0,
      12,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Punch
      shAttack::kPunch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Kick
      shAttack::kKick,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // HeadButt
      shAttack::kHeadButt,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // StrongPunch
      shAttack::kPunch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // StrongKick
      shAttack::kKick,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // StrongHeadButt
      shAttack::kHeadButt,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // XNClaw
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            7,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // XNRake
      shAttack::kRake,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // XNBite
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            9,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // XNTail
      shAttack::kTailSlap,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            5,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Slime
      shAttack::kSlime,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      SLOWTURN,
      {
         {
            kCorrosive,
            1,
            1,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // GridBug
      shAttack::kZap,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      SLOWTURN,
      {
         {
            kElectrical,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // BoreWorm
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      SLOWTURN,
      {
         {
            kHackNSlash,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Tribble
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      SLOWTURN,
      {
         {
            kHackNSlash,
            1,
            2,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // 1_4Smash
      shAttack::kSmash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // 1_6Smash
      shAttack::kSmash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Mynock
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            2,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Cockroach
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kHackNSlash,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ManEater
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kHackNSlash,
            2,
            11,
            100
         },
         {
            kToxic,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Pudding
      shAttack::kSlime,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            2,
            3,
            100
         },
         {
            kParalyzing,
            5,
            20,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Explode
      shAttack::kExplode,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kExplosive,
            6,
            18,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // 1_4Bite
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // 1_6Bite
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // CatbotRake
      shAttack::kRake,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            7,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // VatSlime
      shAttack::kSmash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kCorrosive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Astromech
      shAttack::kZap,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kElectrical,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // CriteTeeth
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      QUICKTURN,
      {
         {
            kHackNSlash,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // CriteQuill
      shAttack::kQuill,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            2,
            100
         },
         {
            kToxic,
            1,
            2,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // StealCredits
      shAttack::kCreditDraining,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kSpecial,
            1,
            200,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Lizard1
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            2,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Lizard2
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            6,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Lizard3
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            6,
            18,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // SewerWorm
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            8,
            14,
            100
         },
         {
            kToxic,
            1,
            2,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // LizardBreath1
      shAttack::kNoAttack,
      shAttack::kSingle,
      kAimed,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // LizardBreath2
      shAttack::kNoAttack,
      shAttack::kSingle,
      kAimed,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // LizardBreath3
      shAttack::kNoAttack,
      shAttack::kSingle,
      kAimed,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PowerfulPunch
      shAttack::kPunch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PowerfulKick
      shAttack::kKick,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // NinjaPunch
      shAttack::kPunch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // NinjaKick
      shAttack::kKick,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // FaceHug
      shAttack::kFaceHug,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // RadBug
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            6,
            100
         },
         {
            kToxic,
            1,
            2,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Chestburster
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      QUICKTURN,
      {
         {
            kHackNSlash,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AlienPrincess
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kHackNSlash,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Recognizer
      shAttack::kStomp,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            3,
            18,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // RadSpider
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            6,
            100
         },
         {
            kToxic,
            1,
            3,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PinkHorror
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      QUICKTURN,
      {
         {
            kHackNSlash,
            2,
            16,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // 1_6Claw
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // BrainExtraction
      shAttack::kExtractBrain,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Docbot1
      shAttack::kSaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            3,
            11,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Docbot2
      shAttack::kDrill,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            3,
            11,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Docbot3
      shAttack::kCut,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            3,
            11,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // SpiderWeb
      shAttack::kWeb,
      shAttack::kSingle,
      kAimed,
      0,
      8,
      0,
      FULLTURN,
      {
         {
            kWebbing,
            3,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Zergling
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kHackNSlash,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ReverendMother
      shAttack::kTouch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kPsychic,
            1,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Troll1
      shAttack::kPunch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            2,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Troll2
      shAttack::kHeadButt,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            2,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // 1_8Claw
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Hydralisk
      shAttack::kSpit,
      shAttack::kSingle,
      kAimed,
      0,
      6,
      0,
      FULLTURN,
      {
         {
            kCorrosive,
            4,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ScorpClaw
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kHackNSlash,
            1,
            4,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ScorpTail
      shAttack::kSting,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            2,
            8,
            100
         },
         {
            kToxic,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // RabbitTeeth
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            6,
            16,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AlienClaw
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kHackNSlash,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AlienTail
      shAttack::kTailSlap,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      SLOWTURN,
      {
         {
            kConcussive,
            2,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AlienBite
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            2,
            10,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // AlienQueenBite
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      QUICKTURN,
      {
         {
            kHackNSlash,
            4,
            16,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Sorceress
      shAttack::kExplode,
      shAttack::kBurst,
      0,
      5,
      5,
      0,
      FULLTURN,
      {
         {
            kPsychic,
            20,
            40,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // SpiderMine
      shAttack::kExplode,
      shAttack::kBurst,
      0,
      1,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            20,
            40,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Monolith
      shAttack::kSmash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            10,
            40,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Clerkbot
      shAttack::kZap,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kElectrical,
            2,
            12,
            100
         },
         {
            kStunning,
            1,
            6,
            25
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Crush
      shAttack::kCrush,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            1,
            15,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // TurretCannon
      shAttack::kShot,
      shAttack::kSingle,
      kAimed,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kBullet,
            5,
            15,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // DefilerMaw
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            3,
            9,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // PLAGUE
      shAttack::kPlague,
      shAttack::kBeam,
      kAimed,
      0,
      4,
      0,
      LONGTURN,
      {
         {
            kIrresistible,
            8,
            20,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // HeavyBotSmash
      shAttack::kSmash,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kConcussive,
            2,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // DalekLaser
      shAttack::kLaserBeam,
      shAttack::kBeam,
      kAimed,
      0,
      30,
      0,
      FULLTURN,
      {
         {
            kLaser,
            8,
            40,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // ApePunch
      shAttack::kPunch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      QUICKTURN,
      {
         {
            kConcussive,
            1,
            6,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // DaemonClaw
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      HALFTURN,
      {
         {
            kHackNSlash,
            1,
            8,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // DaemonBite
      shAttack::kBite,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      QUICKTURN,
      {
         {
            kHackNSlash,
            8,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // NNTPMelee
      shAttack::kScorch,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kBurning,
            7,
            12,
            100
         },
         {
            kHackNSlash,
            4,
            7,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Viruses
      shAttack::kBreatheViruses,
      shAttack::kBeam,
      0,
      0,
      10,
      0,
      FULLTURN,
      {
         {
            kIrresistible,
            6,
            36,
            100
         },
         {
            kSickening,
            10,
            15,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Bugs
      shAttack::kBreatheBugs,
      shAttack::kBeam,
      0,
      0,
      10,
      0,
      FULLTURN,
      {
         {
            kIrresistible,
            6,
            36,
            100
         },
         {
            kBugging,
            1,
            2,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Flamewars
      shAttack::kBreatheFire,
      shAttack::kBeam,
      0,
      0,
      10,
      0,
      FULLTURN,
      {
         {
            kBurning,
            6,
            36,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Traffic
      shAttack::kBreatheTraffic,
      shAttack::kBeam,
      0,
      0,
      10,
      0,
      FULLTURN,
      {
         {
            kIrresistible,
            6,
            36,
            100
         },
         {
            kSpecial,
            10,
            25,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   },
   {  // Shodan
      shAttack::kClaw,
      shAttack::kSingle,
      kMelee,
      0,
      0,
      0,
      FULLTURN,
      {
         {
            kHackNSlash,
            1,
            12,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         },
         {
            kNoEnergy,
            0,
            0,
            100
         }
      }
   }
};
